[황정현] Mission 2: 모델링
wecode-bootcamp-korea/31-westagram-backend-5-team pull request #4
Opened 2022-03-17 07:45 UTC by JeongHyeon-01

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Userㄴ App 생성 및 models 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Users App 생성
- User models 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-17 07:50 UTC, kyeongraekim requested changes

2022-03-17 07:50 UTC, kyeongraekim commented on jeonghyeon/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

2022-03-17 07:50 UTC, kyeongraekim commented on jeonghyeon/users/models.py
> +    email = models.EmailField(max_length=45)
email field에 unique 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
공식 문서에서 그 방법을 찾아보고 적용해주세요.

2022-03-17 07:50 UTC, kyeongraekim commented on jeonghyeon/users/models.py
> +    password = models.CharField(max_length=45)
비밀번호는 향후 암호화(해싱) 되어 디비에 저장될 예정임으로 비밀번호는 최소한 100자 이상으로 잡아주세요!~

2022-03-17 07:50 UTC, kyeongraekim commented on jeonghyeon/users/models.py
> +        return self.name
모델의 핵심인 아래의 내용이 빠져있네요!

```python
  
    class Meta: 
        db_table = "users"

2022-03-17 07:50 UTC, kyeongraekim commented on jeonghyeon/users/models.py
> +# Create your models here.
불필요한 주석은 삭제해주세요!~

2022-03-17 07:51 UTC, JeongHyeon-01 commented
Settings.py 에 users앱 추가후 migrate 완료 해서 다시 커밋합니다

2022-03-17 07:57 UTC, JeongHyeon-01 commented
모델부분 수정완료 created_at, updated_at 추가 및 이메일필드 unique 추가 완료

2022-03-17 07:59 UTC, JeongHyeon-01 commented
migrate 파일 초기화 후 다시 migrate완료

2022-03-18 01:24 UTC, kyeongraekim requested changes

2022-03-18 01:24 UTC, kyeongraekim commented on jeonghyeon/users/models.py
> +    phone =models.CharField(max_length=45)
전화번호 쪽 = 이후에 스페이스 공백이 한 번 들어가야 정렬이 맞을 것 같네요! 푸시 전에 전반적인 정렬 여부, 포맷 등을 깔끔하게 확인해주시는 것도 늘 내코드를 다른 사람에게 보여주며 협업해야하는, 개발자의 필수 덕목이오니 참고바랍니다!~

2022-03-18 04:44 UTC, JeongHyeon-01 commented
![image](https://user-images.githubusercontent.com/89664413/158938942-6370a444-baeb-4878-818a-8e42cecc76d3.png)
수정완료

2022-03-18 05:17 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-18 05:17 UTC, merged