[황정현] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/31-westagram-backend-5-team pull request #6
Opened 2022-03-18 07:44 UTC by JeongHyeon-01

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- url 경로수정, 회원가입 로직 구현
- 
- ## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 기능구현 (데이터 입력이 없으면 에러반환(400) 비밀번호 및 이메일 유효성검사 실패시 에러 반환 )
- URL 경로 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- Class로 따로 유효성 검사부분을 다루고 싶은데 따로 빼니까 검사가 실패하는것 같습니다. 이부분을 구현  해보고싶습니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-20 06:48 UTC, JeongHyeon-01 commented
1. vaildation 부분을 vaildation.py 로 따로빼서 추후에 관리가 편하게 수정하였습니다.
2. app 추가될것을 대비하여 users/signin 페이지로 빠지게 만들어두었습니다.
3. view로직 수정 했습니다.

2022-03-21 05:38 UTC, bigfanoftim requested changes

2022-03-21 05:38 UTC, bigfanoftim commented on students/jeonghyeon/users/vaildation.py
> +def Vaildation_email(email):
함수는 동사이며 대문자를 쓰지 않습니다.
```suggestion
def vaildate_email(email):
```

2022-03-21 05:38 UTC, bigfanoftim commented on students/jeonghyeon/users/vaildation.py
> +        raise ValidationError('Check_email')
에러를 리턴해줄거면 보다 명확한 메시지가 필요할 것 같습니다.
```suggestion
        raise ValidationError('INVALID_EMAIL')
```

2022-03-21 05:43 UTC, JeongHyeon-01 commented on students/jeonghyeon/users/vaildation.py
> +def Vaildation_email(email):
소문자 수정완료

2022-03-21 05:43 UTC, JeongHyeon-01 commented on students/jeonghyeon/users/vaildation.py
> +        raise ValidationError('Check_email')
명확한 에러메시지로 변경 완료

2022-03-21 06:15 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-21 06:15 UTC, merged