[ADD]Signin View
wecode-bootcamp-korea/31-westagram-backend-5-team pull request #8
Opened 2022-03-21 06:34 UTC by JeongHyeon-01

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 구현 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일과 비밀번호 정상입력시 Sucess 도출 
- KEYERROR 및  Invailduser 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-21 07:30 UTC, JeongHyeon-01 commented
Exceptions 에러 에서 KeyError로 변경 완료

2022-03-21 07:47 UTC, sangahnhan reviewed
LGTM 👍

2022-03-22 01:16 UTC, kyeongraekim requested changes

2022-03-22 01:16 UTC, kyeongraekim commented on students/jeonghyeon/users/urls.py
> +    path('/signup',SignUpView.as_view()),
컨벤션 정렬 일치화를 위해 쉼표 뒤에 스페이싱 한칸 해주세요~

2022-03-22 01:16 UTC, kyeongraekim commented on students/jeonghyeon/users/views.py
> +                else:
이곳에서의 else로의 추가 분기가 꼭 필요해보일 것 같지는 않은데 해당 이유에 대해서 곰곰히 생각해보세요!~

2022-03-22 03:40 UTC, JeongHyeon-01 commented on students/jeonghyeon/users/urls.py
> +    path('/signup',SignUpView.as_view()),
수정완료 했습니다

2022-03-22 03:40 UTC, JeongHyeon-01 commented on students/jeonghyeon/users/views.py
> +                else:
수정완료 했습니다

2022-03-22 05:45 UTC, bigfanoftim requested changes

2022-03-22 05:45 UTC, bigfanoftim commented on students/jeonghyeon/users/views.py
> +                return JsonResponse( {"message": "INVALID_USER"}, status=401)
실패 케이스를 if문으로 처리해주시면 더 좋을것 같아요~

2022-03-22 07:00 UTC, bigfanoftim requested changes
간단한 수정사항 적용 후 바로 푸시해주세요!

2022-03-22 07:00 UTC, bigfanoftim commented on students/jeonghyeon/users/urls.py
>  from django.urls import path
```suggestion
from django.urls import path

```

2022-03-22 07:00 UTC, bigfanoftim commented on students/jeonghyeon/users/views.py
> +                return JsonResponse( {"message": "KEYERROR"}, status=400)
에러메시지 양식은 통일해주는게 좋습니다.
```suggestion
                return JsonResponse({"message": "SUCCESS" }, status = 200)
                
            except KeyError:
                return JsonResponse( {"message": "KEY_ERROR"}, status=400)
```

2022-03-22 07:12 UTC, JeongHyeon-01 commented on students/jeonghyeon/users/urls.py
>  from django.urls import path
dj

2022-03-22 07:13 UTC, JeongHyeon-01 commented on students/jeonghyeon/users/views.py
> +                return JsonResponse( {"message": "KEYERROR"}, status=400)
수정완료

2022-03-22 07:17 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-22 07:17 UTC, merged