[한상안] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/31-westagram-backend-5-team pull request #9
Opened 2022-03-21 08:37 UTC by sangahnhan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 유저 로그인 구현
		 
## 수정 사항들 자세한 내용
- 로그인 view 구현
- 로그인 validation 구현
- 오류수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-21 08:48 UTC, JeongHyeon-01 commented on students/sangahn/users/views.py
>              validate_sign_up(id,password)
변수명 id 가 user id 인지 email 인지 혼동 될수 있을거 같습니다. 👍  로그인 모듈화 해서 넣어둔게 깔끔한거 같습니다. good

2022-03-22 01:12 UTC, kyeongraekim requested changes

2022-03-22 01:12 UTC, kyeongraekim commented on students/sangahn/users/validator.py
> +PASSWORD_FORMAT = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$'
정규표현식임을 알수 있게 자주 사용하는 약어인 REGEX  라는 용어로 대체해주세요

2022-03-22 01:12 UTC, kyeongraekim commented on students/sangahn/users/validator.py
> +def overlap_email(email):
overlap 보다는 중복의 의미표현시 자주 사용하는 check_email_duplication 정도가 더 나은 함수 네이밍으로 보여지네요~

2022-03-22 01:12 UTC, kyeongraekim commented on students/sangahn/users/views.py
> +            overlap_email(email)
코드 논리 흐름상 email에대한 검증을 다 마치고 패스워드 검증으로 넘어가면 더 효율적으로 보일 것 같습니다~

2022-03-22 01:12 UTC, kyeongraekim commented on students/sangahn/users/views.py
> +            return JsonResponse({"message" : "SUCCESS"} , status=200)
가독성을 위해 리턴문 시작에 앞서 한 줄의 스페이싱을 해주세요~

2022-03-22 01:12 UTC, kyeongraekim commented on students/sangahn/users/views.py
> +            validate_sign_up(email,password)
로그인 sign_in에 대한 view인데 validate는 sign_up으로 해주시고 계시네요~ 한 번 다시 확인 부탁드립니다!

2022-03-22 01:29 UTC, ddangahn2 commented on students/sangahn/users/validator.py
> +PASSWORD_FORMAT = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$'
네 EMAIL_REGEX, PASSWORD_REGEX 로 교체했습니다

2022-03-22 01:30 UTC, sangahnhan commented on students/sangahn/users/validator.py
> +def overlap_email(email):
네 함수 이름과 raise ValidationError("EMAIL_DUPLICATE_ERROR") 로 메세지 수정했습니다

2022-03-22 01:30 UTC, sangahnhan commented on students/sangahn/users/views.py
> +            overlap_email(email)
넵 위치 수정 했습니다

2022-03-22 01:31 UTC, sangahnhan commented on students/sangahn/users/views.py
> +            validate_sign_up(email,password)
스페이싱 및 함수 이름 네이밍 sign_up -> sign_in 으로 수정했습니다

2022-03-22 06:39 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-22 06:40 UTC, merged